add_lunch_combo par_bacon-userdebug
add_lunch_combo par_falcon-userdebug
add_lunch_combo par_ghost-userdebug
add_lunch_combo par_grouper-userdebug
add_lunch_combo par_m8-userdebug
add_lunch_combo par_tilapia-userdebug
